### PR TITLE
Scoring scenario + refinement scenario + alascan page

### LINKED ISSUE #138: Scoring scenario
**Is your feature request related to a problem? Please describe.**
Have a scenario that does not do docking.
Run workflow like https://github.com/haddocking/haddock3/blob/main/examples/scoring/capri-scoring-test.cfg
where user upload multiple molecules and gets back score per molecule, residue, cluster

residue score needs alascan

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### LINKED ISSUE #139: link to alascan html files
The alascan module outputs html files. Would be nice in the webapp to have a quick link to those html files.

### LINKED ISSUE #143: Refine scenario
**Is your feature request related to a problem? Please describe.**
A refinement scenario page which runs workflow based on https://github.com/haddocking/haddock3/blob/main/examples/refine-complex/refine-complex-test.cfg with contactmap and alascan modules added.

**Additional context**
Spawned from https://github.com/i-VRESSE/haddock3-webapp/pull/140#issuecomment-2312489571

### PR DESCRIPTION
**Pull request by sverhoeven**
Fixes #138
Fixes #139 
Fixes #143 

To test upload https://github.com/haddocking/haddock3/blob/main/examples/scoring/data/T161-rescoring-ens.pdb

TODO
* [x] latest haddock3 is used, with no 'The following error occurred 1' errors
* [x] alascan report, it generates plot per cluster, should have page that shows all clusters
* [x] show alascan score in 3D?
* [x] show score in 3D
* [x] show scores of molecules without clustering? look at 2_caprieval module output
* [x] allow user to adjust clustering?
* [x] include caprieval score without clustering?
* [x] scoring page
* [x] refinement page
* [x] handle non-easy parameters in workflow.cfg, see comment below

Scoring Scenario page
localhost_3000_scenarios_scoring

Scoring Scenario result
localhost_3000_jobs

Refinement scenario page
0 0 0 0_3000_jobs_9_browse (2)

Refinement scenario result
0 0 0 0_3000_jobs_9_browse

Alascan page
0 0 0 0_3000_jobs_5_analysis_alascan_8_1

### CODE REVIEW

**Comment by sverhoeven** [comment]
@VGPReys could you have a look at the screenshots?

And have a look at the constructed workflow at https://github.com/i-VRESSE/haddock3-webapp/blob/9ddb448553574c3a62e427d49ab883cd7a2a74d7/app/routes/scenarios.scoring.tsx#L58-L95

**Comment by sverhoeven** [comment]
@VGPReys 
1. How could I include scores of unclustered molecules, add caprieval before clustfcc? 
2. Should an user be allowed to set clustering parameters? if so which ones and how much?

**Comment by VGPReys** [comment]
@sverhoeven 
For the workflow, I would rather go for something like:
```toml
# =================================================================================== 
 # CAPRI Scoring example 
 # =================================================================================== 
 # The Critical Assessment of PRedicted Interactions (CAPRI) experiment 
 #  aims to do test methods that model macromolecular interactions in 
 #  blind predictions based on the three-dimensional structures of proteins. 
 # For more information, please visit: https://www.ebi.ac.uk/pdbe/complex-pred/capri/ 
 # =================================================================================== 
 run_dir = "${JOB_OUTPUT_DIR}" 
  
 # molecules to be scored (an ensemble PBD) 
 molecules = ${molecules} 
  
 # =================================================================================== 
 [topoaa] 
  
 [emscoring] 
  
 [caprieval] 

 [clustfcc] 
 min_population = 1
 plot_matrix = true 
  
 [seletopclusts] 
 top_models = 4
  
 [alascan]

 [caprieval] 
  
 # =================================================================================== 
```

- removing `[mdscoring]` as it is too costly.
- adding a `caprieval` after `emscoring` (related to your point `1`)
- removing `top_cluster = 1`, so we retrieve all clusters.

>     2. Should an user be allowed to set clustering parameters? if so which ones and how much?
Yes, a user could be able to tune clustering parameters.
I would make visible:`min_population` and `clust_cutoff`.
Maybe also `top_models` and `top_cluster` from `[seletopclusts]`.

**Comment by VGPReys** [comment]
I was thinking that I could bring interesting insights on what are the key components for the interaction.
Not required.
You have the last words ;)

**Comment by VGPReys** [comment]
@sverhoeven 
Also, this scenario could handle multiple input files (up to 20).

**Comment by VGPReys** [comment]
ok @sverhoeven , after some discussion with Alex, we decided to:

- remove both `[alascan]` and `[contactmap]` from the scoring scenario, as it may generate too many plots and take too much time (we could expect user providing thousands of models)

But those two modules will be part of the refinement scenario.

**Comment by sverhoeven** [comment]
Ah yes without mdscoring it takes 18 seconds for https://github.com/haddocking/haddock3/blob/main/examples/scoring/data/T161-rescoring-ens.pdb

**Comment by sverhoeven** [comment]
> * adding tolerance to make sure the workflow will terminate successfully.

tolerance is a expert parameter with default 0. So a user with only easy expertise level will get an error that they are not allowed to use that parameter. 

The webapp uses same endpoint to upload workflow from scenario, build, upload pages. I can not have an endpoint that accepts parameters not part of the users level, because that could be misused.

What should I do?
1. Do not set tolerance parameter when user has easy level, but do set when expert or guru
2. Change default to 10
3. Move tolerance to easy level

Where should I do it?
1. In haddock3 defaults.yaml
2. In workflow builder
5. In haddock3 webapp,

**Comment by sverhoeven** [comment]
For now picked 1 for what and 3 for where, but this gives users with easy level worst results.

**Comment by sverhoeven** [comment]
Some other PRs where merged into this branch, please review by focusing on functionality or this pr not the other prs.

**Comment by sverhoeven** [comment]
Sorry review is taking to long, merging it, review can be done on merge pr if needed.

**Pull request merged**
